# Generated by Django 4.0.1 on 2022-01-31 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bike',
            name='station',
        ),
    ]
