# Generated by Django 4.0.1 on 2022-02-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='image',
            field=models.URLField(null=True),
        ),
    ]
