# Generated by Django 4.0.1 on 2022-02-09 11:33

from django.db import migrations, models
import onbici.station.models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0002_station_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='image',
            field=models.ImageField(default='stations/default.jpg', upload_to=onbici.station.models.upload_to, verbose_name='Image'),
        ),
    ]
