# Generated by Django 4.0.1 on 2022-02-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0004_alter_station_latitude_alter_station_longitude'),
        ('bike', '0002_remove_bike_station'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('bike', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bike.bike')),
                ('station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='station.station')),
            ],
        ),
    ]
