# Generated by Django 4.0.1 on 2022-05-11 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_profile_stripe_customer_id_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.TextField(blank=True, default='https://avatars.dicebear.com/api/avataaars/AVXL1736P.svg'),
        ),
    ]
