# Generated by Django 4.0.1 on 2022-05-08 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rates',
            name='stripe_price_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
