# Generated by Django 4.0.1 on 2022-02-21 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('slot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='end_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_slot', to='slot.slot'),
        ),
        migrations.AddField(
            model_name='rent',
            name='start_slot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='start_slot', to='slot.slot'),
        ),
        migrations.AddField(
            model_name='rent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
