# Generated by Django 4.0.1 on 2022-05-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_subscription_id', models.CharField(max_length=500, null=True)),
                ('customer', models.CharField(max_length=500, null=True)),
                ('period_start', models.DateTimeField(null=True)),
                ('period_end', models.DateTimeField(null=True)),
                ('cancel_at_period_end', models.BooleanField(null=True)),
                ('cancel_at', models.DateTimeField(null=True)),
                ('ended_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
